// <auto-generated />
namespace ExamSkillProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class skillscompanyIDresetv0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(skillscompanyIDresetv0));
        
        string IMigrationMetadata.Id
        {
            get { return "201612140056430_skills+companyIDresetv0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
